# VVU CI/CD Trust Chain v3.1 - Manifest Signature Placeholder
# This file will be generated by running:
#   node packages/trust-crypto/dist/sign.js .manifest.json --key $MANIFEST_SIGNING_KEY > .manifest.json.sig
# Replace this placeholder with the actual Ed25519 signature.
PLACEHOLDER_SIGNATURE
