#!/bin/bash
# Bayesian Sentinel — One-Click Droplet Deployment
# Run this script from your local machine (not on the droplet)
# It will SSH into the droplet and execute the full deployment

set -e

DROPLET_IP="165.245.140.197"
DROPLET_USER="root"
SSH_KEY="$HOME/.ssh/id_ed25519_droplet_prod"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}[BAYESIAN SENTINEL]${NC} Starting autonomous deployment..."

# Check SSH key exists
if [ ! -f "$SSH_KEY" ]; then
    echo -e "${RED}[ERROR]${NC} SSH key not found at $SSH_KEY"
    echo "Generate one with: ssh-keygen -t ed25519 -f $SSH_KEY -N ''"
    exit 1
fi

SSH_CMD="ssh -i $SSH_KEY -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 ${DROPLET_USER}@${DROPLET_IP}"

echo -e "${BLUE}[1/6]${NC} Verifying droplet connectivity..."
$SSH_CMD 'echo "Droplet reachable"' || {
    echo -e "${RED}[FATAL]${NC} Cannot connect to $DROPLET_IP"
    echo "Make sure your SSH public key is added to /root/.ssh/authorized_keys via Web Console"
    exit 1
}

echo -e "${GREEN}[OK]${NC} Droplet connected"

echo -e "${BLUE}[2/6]${NC} Syncing repository..."
$SSH_CMD '
    set -e
    cd /root/proofbridge-liner
    git pull origin main || {
        echo "First-time clone or repo missing"
        exit 1
    }
    echo "Repository synced"
' || {
    echo -e "${RED}[FATAL]${NC} Git pull failed. Ensure repo exists at /root/proofbridge-liner"
    exit 1
}

echo -e "${GREEN}[OK]${NC} Repository updated"

echo -e "${BLUE}[3/6]${NC} Deploying .env.deployed..."
$SSH_CMD '
    set -e
    cat > /root/proofbridge-liner/.env.deployed << "ENVEOF"
# ProofBridge Liner — deployed addresses
# Generated by scripts/deploy.js on 2026-05-10T00:13:23.209Z
# Network: Polygon Amoy (chainId 80002)

CIRCUIT_BREAKER_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
ASSET_REGISTRY_ADDRESS=0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
TEE_VERIFIER_ADDRESS=0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
ORACLE_ADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
ENCLAVE_ADDRESS=0x70997970c51812dc3a010c7d01b50e0d17dc79c8
ENVEOF
    echo ".env.deployed written"
'

echo -e "${GREEN}[OK]${NC} Environment file deployed"

echo -e "${BLUE}[4/6]${NC} Restarting proofbridge service..."
$SSH_CMD '
    set -e
    systemctl daemon-reload
    systemctl restart proofbridge
    sleep 3
    if systemctl is-active --quiet proofbridge; then
        echo "Service is active"
    else
        echo "Service failed!"
        systemctl status proofbridge --no-pager -l
        exit 1
    fi
' || {
    echo -e "${RED}[FATAL]${NC} Service failed to start"
    exit 1
}

echo -e "${GREEN}[OK]${NC} Service restarted"

echo -e "${BLUE}[5/6]${NC} Verifying health endpoint..."
$SSH_CMD '
    set -e
    HTTP_CODE=$(curl -sf -o /dev/null -w "%{http_code}" http://localhost:7860/health 2>/dev/null || echo "000")
    if [ "$HTTP_CODE" = "200" ]; then
        echo "Health check PASSED (HTTP 200)"
        curl -s http://localhost:7860/health
    else
        echo "Health check FAILED (HTTP $HTTP_CODE)"
        exit 1
    fi
' || {
    echo -e "${RED}[WARN]${NC} Health endpoint not responding yet (may need more time)"
}

echo -e "${GREEN}[OK]${NC} System operational"

echo -e "${BLUE}[6/6]${NC} Final service status..."
$SSH_CMD 'systemctl status proofbridge --no-pager'

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  BAYESIAN SENTINEL — DEPLOYMENT COMPLETE${NC}"
echo -e "${GREEN}  Droplet: $DROPLET_IP${NC}"
echo -e "${GREEN}  Dashboard: http://$DROPLET_IP:7860${NC}"
echo -e "${GREEN}  API Status: http://$DROPLET_IP:7860/api/status${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════${NC}"
echo ""
echo "Next steps:"
echo "1. Open browser to: http://165.245.140.197:7860"
echo "2. Verify 'CircuitBreakerV2 Active' in dashboard"
echo "3. Run final recorded walkthrough"
echo ""
