#!/usr/bin/env python3
"""
VVU HBK Mk-II Terminal-as-a-Service (TaaS) Commercial Framework Specification
Body PDF generator via ReportLab.

Follows the Report brief production workflow:
- TocDocTemplate for Table of Contents
- Cascade palette for color system
- Professional typography hierarchy
- Page numbering (Arabic, centered footer)
"""

import hashlib
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm, inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, CondPageBreak, KeepTogether, HRFlowable, Flowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.platypus.frames import Frame
from reportlab.platypus.doctemplate import PageTemplate, BaseDocTemplate

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━

# XL tier: backgrounds (area > 50%, S <= 0.08)
PAGE_BG       = colors.HexColor('#f6f6f5')
SECTION_BG    = colors.HexColor('#eeeeec')

# L tier: surfaces (area 20-50%, S <= 0.15)
CARD_BG       = colors.HexColor('#f0efee')
TABLE_STRIPE  = colors.HexColor('#eeedeb')

# M tier: structural fills (area 5-20%, S <= 0.30)
HEADER_FILL   = colors.HexColor('#514931')
COVER_BLOCK   = colors.HexColor('#5f5947')

# S tier: edges & icons (area 1-5%, S <= 0.50)
BORDER        = colors.HexColor('#cec9b8')
ICON          = colors.HexColor('#b19746')

# XS tier: emphasis (area < 1%, S <= 0.75)
ACCENT        = colors.HexColor('#8e7324')
ACCENT_2      = colors.HexColor('#4296b2')

# Typography
TEXT_PRIMARY   = colors.HexColor('#242320')
TEXT_MUTED     = colors.HexColor('#87847d')

# VVU Gold accent for branding emphasis
VVU_GOLD      = colors.HexColor('#C9A84C')

# Semantic (low-saturation)
SEM_SUCCESS   = colors.HexColor('#458259')
SEM_WARNING   = colors.HexColor('#a18650')
SEM_ERROR     = colors.HexColor('#a85952')
SEM_INFO      = colors.HexColor('#406991')

# Table colors (derived from cascade tiers)
TABLE_HEADER_COLOR = HEADER_FILL
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ─── Page Dimensions ───
PAGE_WIDTH, PAGE_HEIGHT = A4  # 595.27 x 841.89 points
LEFT_MARGIN = 2.2 * cm
RIGHT_MARGIN = 2.2 * cm
TOP_MARGIN = 2.5 * cm
BOTTOM_MARGIN = 2.5 * cm
CONTENT_WIDTH = PAGE_WIDTH - LEFT_MARGIN - RIGHT_MARGIN

OUTPUT_PATH = '/home/z/my-project/outreach-docs/taas-body.pdf'

# ─── Styles ───
def create_styles():
    styles = getSampleStyleSheet()

    # H1 — Section title
    styles.add(ParagraphStyle(
        name='H1',
        fontName='Helvetica-Bold',
        fontSize=18,
        leading=22,
        textColor=HEADER_FILL,
        spaceBefore=24,
        spaceAfter=12,
        alignment=TA_LEFT,
    ))

    # H2 — Subsection title
    styles.add(ParagraphStyle(
        name='H2',
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=ACCENT,
        spaceBefore=16,
        spaceAfter=8,
        alignment=TA_LEFT,
    ))

    # H3 — Minor heading
    styles.add(ParagraphStyle(
        name='H3',
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=14,
        textColor=TEXT_PRIMARY,
        spaceBefore=10,
        spaceAfter=6,
        alignment=TA_LEFT,
    ))

    # Body text
    styles.add(ParagraphStyle(
        name='BodyTaaS',
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_PRIMARY,
        alignment=TA_JUSTIFY,
        spaceBefore=3,
        spaceAfter=6,
    ))

    # Bullet text
    styles.add(ParagraphStyle(
        name='BulletTaaS',
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_PRIMARY,
        leftIndent=18,
        spaceBefore=2,
        spaceAfter=3,
    ))

    # Bold emphasis
    styles.add(ParagraphStyle(
        name='EmphasisTaaS',
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=ACCENT,
        spaceBefore=3,
        spaceAfter=6,
    ))

    # Callout box text
    styles.add(ParagraphStyle(
        name='CalloutTaaS',
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=13,
        textColor=VVU_GOLD,
        leftIndent=12,
        spaceBefore=4,
        spaceAfter=4,
    ))

    # Table header
    styles.add(ParagraphStyle(
        name='TH',
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=TABLE_HEADER_TEXT,
        alignment=TA_CENTER,
    ))

    # Table cell
    styles.add(ParagraphStyle(
        name='TC',
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=TEXT_PRIMARY,
        alignment=TA_LEFT,
    ))

    # Table cell centered
    styles.add(ParagraphStyle(
        name='TCC',
        fontName='Helvetica',
        fontSize=8.5,
        leading=11,
        textColor=TEXT_PRIMARY,
        alignment=TA_CENTER,
    ))

    # TOC Level 0
    styles.add(ParagraphStyle(
        name='TOC0',
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=HEADER_FILL,
        spaceBefore=8,
        spaceAfter=4,
        leftIndent=0,
    ))

    # TOC Level 1
    styles.add(ParagraphStyle(
        name='TOC1',
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=TEXT_PRIMARY,
        spaceBefore=4,
        spaceAfter=2,
        leftIndent=24,
    ))

    # Footer page number
    styles.add(ParagraphStyle(
        name='PageNum',
        fontName='Helvetica',
        fontSize=9,
        leading=11,
        textColor=TEXT_MUTED,
        alignment=TA_CENTER,
    ))

    return styles


# ─── TocDocTemplate (for TOC support) ───
class TocDocTemplate(BaseDocTemplate):
    """Custom DocTemplate that supports Table of Contents via afterFlowable.
    Inherits from BaseDocTemplate so we can control page templates directly."""
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


# ─── Heading helper (with bookmark for TOC) ───
def add_heading(text, style, level=0):
    key = f'h_{hashlib.md5(text.encode()).hexdigest()[:8]}'
    p = Paragraph(f'<a name="{key}"/>{text}', style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


# ─── Page number footer ───
def footer_arabic(canvas, doc):
    """Arabic page number, centered in footer."""
    canvas.saveState()
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawCentredString(PAGE_WIDTH / 2, BOTTOM_MARGIN - 12 * mm, str(doc.page))
    # Thin decorative line above footer
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(LEFT_MARGIN, BOTTOM_MARGIN - 4 * mm, PAGE_WIDTH - RIGHT_MARGIN, BOTTOM_MARGIN - 4 * mm)
    canvas.restoreState()


# ─── Custom Flowables ───
class GoldRule(Flowable):
    """A thin gold horizontal rule for section emphasis."""
    def __init__(self, width, thickness=1.5, color=VVU_GOLD):
        Flowable.__init__(self)
        self.width = width
        self.thickness = thickness
        self.color = color
        self.height = thickness + 4

    def draw(self):
        self.canv.setStrokeColor(self.color)
        self.canv.setLineWidth(self.thickness)
        self.canv.line(0, 2, self.width, 2)


class SectionDivider(Flowable):
    """A wider section divider with gold accent line and muted text."""
    def __init__(self, width, label=''):
        Flowable.__init__(self)
        self.width = width
        self.label = label
        self.height = 18

    def draw(self):
        self.canv.setStrokeColor(BORDER)
        self.canv.setLineWidth(0.5)
        self.canv.line(0, 10, self.width, 10)
        if self.label:
            self.canv.setFont('Helvetica', 7)
            self.canv.setFillColor(TEXT_MUTED)
            self.canv.drawString(4, 2, self.label)


# ─── Build the Story ───
def build_story(styles):
    story = []

    # ── Table of Contents ──
    toc = TableOfContents()
    toc.levelStyles = [styles['TOC0'], styles['TOC1']]
    story.append(Paragraph('Table of Contents', styles['H1']))
    story.append(Spacer(1, 8))
    story.append(toc)
    story.append(PageBreak())

    # ════════════════════════════════════════════════════════
    # SECTION 1: Service Definition — Terminal-as-a-Service (TaaS)
    # ════════════════════════════════════════════════════════
    story.append(add_heading('1. Service Definition — Terminal-as-a-Service (TaaS)', styles['H1'], level=0))
    story.append(GoldRule(CONTENT_WIDTH))
    story.append(Spacer(1, 6))

    story.append(add_heading('1.1 The TaaS Value Proposition', styles['H2'], level=1))
    story.append(Paragraph(
        'The Terminal-as-a-Service (TaaS) model represents a fundamental strategic pivot from '
        'traditional CapEx-based hardware procurement toward a Non-Recourse OpEx Treatment framework '
        'for municipal water infrastructure. Under conventional procurement paradigms, municipalities '
        'are compelled to allocate substantial upfront capital for hardware acquisition, installation, '
        'and commissioning—creating an immediate balance sheet liability with no guarantee of operational '
        'performance or data yield. The TaaS framework eliminates this structural inefficiency by '
        'transferring the entire hardware lifecycle—from manufacturing through deployment, maintenance, '
        'and eventual decommissioning—under VVU\'s operational umbrella.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        'The key value propositions of the TaaS model are threefold. First, <b>Balance Sheet De-risking</b>: '
        'municipalities receive the HBK Mk-II Hydro-Gateway Assembly as a fully operational service unit '
        'without assuming ownership liability. The hardware remains on VVU\'s balance sheet, not the '
        'client\'s, ensuring that depreciation risk, obsolescence exposure, and residual value uncertainty '
        'are entirely absorbed by VVU. Second, <b>Elimination of Municipal Upfront Capital Constraints</b>: '
        'the subscription-based OpEx structure allows municipalities to deploy advanced leak-localization '
        'infrastructure within existing operational budgets, bypassing the often-prohibitive CapEx approval '
        'cycles that delay critical infrastructure modernization by years. Third, <b>Performance-Linked '
        'Alignment</b>: because VVU retains 100% equity and sole data sovereignty, the commercial incentive '
        'is directly coupled to operational excellence—VVU profits only when the terminal delivers measurable '
        'infrastructure intelligence.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('1.2 Asset Identification — HBK Mk-II / Hydro-Gateway Assembly', styles['H2'], level=1))
    story.append(Paragraph(
        'The HBK Mk-II Hydro-Gateway Assembly comprises 11 integrated components, each positioned within '
        'a precise XYZ coordinate framework that defines the physical architecture of the terminal. This '
        'assembly represents a complete, self-contained water infrastructure intelligence unit—from primary '
        'flow measurement at the inlet to secure telemetry transmission at the mast apex. The coordinate '
        'system establishes the spatial relationships necessary for structural integrity, hydraulic coupling, '
        'and Bayesian inference processing. Each component serves a defined functional role within the '
        'Observation Vector (O_t) generation pipeline.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 8))

    # ── Asset Identification Table ──
    asset_data = [
        [Paragraph('<b>Component</b>', styles['TH']),
         Paragraph('<b>X (mm)</b>', styles['TH']),
         Paragraph('<b>Y (mm)</b>', styles['TH']),
         Paragraph('<b>Z (mm)</b>', styles['TH']),
         Paragraph('<b>Functional Role</b>', styles['TH'])],
        [Paragraph('Pressure Pipe', styles['TC']),
         Paragraph('0', styles['TCC']),
         Paragraph('0', styles['TCC']),
         Paragraph('750', styles['TCC']),
         Paragraph('Nodal Head Estimation', styles['TC'])],
        [Paragraph('South Datum Skid', styles['TC']),
         Paragraph('0', styles['TCC']),
         Paragraph('-560', styles['TCC']),
         Paragraph('40', styles['TCC']),
         Paragraph('Base structural support', styles['TC'])],
        [Paragraph('North Datum Skid', styles['TC']),
         Paragraph('0', styles['TCC']),
         Paragraph('+560', styles['TCC']),
         Paragraph('40', styles['TCC']),
         Paragraph('Base structural support', styles['TC'])],
        [Paragraph('Left Service Rack', styles['TC']),
         Paragraph('-720', styles['TCC']),
         Paragraph('-240', styles['TCC']),
         Paragraph('290', styles['TCC']),
         Paragraph('Lateral mounting', styles['TC'])],
        [Paragraph('Right Service Rack', styles['TC']),
         Paragraph('+720', styles['TCC']),
         Paragraph('+240', styles['TCC']),
         Paragraph('290', styles['TCC']),
         Paragraph('Lateral mounting', styles['TC'])],
        [Paragraph('Edge Control Cabinet', styles['TC']),
         Paragraph('0', styles['TCC']),
         Paragraph('+400', styles['TCC']),
         Paragraph('400', styles['TCC']),
         Paragraph('Local probabilistic processing / Bayesian inference', styles['TC'])],
        [Paragraph('Power Backup Module', styles['TC']),
         Paragraph('0', styles['TCC']),
         Paragraph('-400', styles['TCC']),
         Paragraph('400', styles['TCC']),
         Paragraph('Power redundancy', styles['TC'])],
        [Paragraph('Inlet Meter Pod', styles['TC']),
         Paragraph('-750', styles['TCC']),
         Paragraph('-160', styles['TCC']),
         Paragraph('930', styles['TCC']),
         Paragraph('Primary flow measurement', styles['TC'])],
        [Paragraph('Outlet Meter Pod', styles['TC']),
         Paragraph('+750', styles['TCC']),
         Paragraph('+160', styles['TCC']),
         Paragraph('930', styles['TCC']),
         Paragraph('Secondary flow measurement', styles['TC'])],
        [Paragraph('Telemetry Mast', styles['TC']),
         Paragraph('0', styles['TCC']),
         Paragraph('0', styles['TCC']),
         Paragraph('1290', styles['TCC']),
         Paragraph('Secure data transmission', styles['TC'])],
        [Paragraph('Top Height Beacon', styles['TC']),
         Paragraph('+100', styles['TCC']),
         Paragraph('0', styles['TCC']),
         Paragraph('1465', styles['TCC']),
         Paragraph('Physical site identification / Aviation safety', styles['TC'])],
    ]

    col_widths = [CONTENT_WIDTH * 0.22, CONTENT_WIDTH * 0.10, CONTENT_WIDTH * 0.10,
                  CONTENT_WIDTH * 0.10, CONTENT_WIDTH * 0.48]

    asset_table = Table(asset_data, colWidths=col_widths, repeatRows=1)
    asset_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 5), (-1, 5), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 6), (-1, 6), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 7), (-1, 7), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 8), (-1, 8), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 9), (-1, 9), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 10), (-1, 10), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 11), (-1, 11), TABLE_ROW_EVEN),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(asset_table)
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        'The coordinate architecture ensures that each component\'s spatial placement optimizes '
        'for signal propagation, structural load distribution, and hydraulic flow continuity. The '
        'datum skids (North and South) anchor the assembly to the installation surface, while the '
        'service racks provide lateral stability. The Edge Control Cabinet houses the Bayesian inference '
        'engine that transforms raw sensor observations into probabilistic leak-localization outputs. '
        'The dual meter pods (Inlet and Outlet) generate the differential flow measurements essential '
        'for the Observation Vector, and the Telemetry Mast transmits encrypted data packets to VVU\'s '
        'central processing infrastructure.',
        styles['BodyTaaS']
    ))

    # ════════════════════════════════════════════════════════
    # SECTION 2: Core Commercial Pillars
    # ════════════════════════════════════════════════════════
    story.append(CondPageBreak(PAGE_HEIGHT * 0.25))
    story.append(add_heading('2. Core Commercial Pillars', styles['H1'], level=0))
    story.append(GoldRule(CONTENT_WIDTH))
    story.append(Spacer(1, 6))

    story.append(add_heading('2.1 100% Equity Retention', styles['H2'], level=1))
    story.append(Paragraph(
        'VVU maintains absolute ownership of every HBK Mk-II Hydro-Gateway Assembly deployed under '
        'the TaaS framework. This is not a lease arrangement with transfer provisions, nor a financed '
        'purchase with a vesting schedule—it is an uncompromised equity position that persists from '
        'manufacturing through deployment, operation, and eventual decommissioning or redeployment. '
        'The 100% equity retention principle serves three critical commercial functions.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        '<b>Non-Transferable Rights</b>: No client, partner, or third party may acquire ownership '
        'stakes in the deployed hardware. This ensures that VVU\'s commercial relationship with the '
        'municipality remains a pure service contract—the client pays for intelligence delivery, not '
        'asset acquisition. The hardware never becomes a liability on the client\'s balance sheet, '
        'and VVU never dilutes its control over the terminal\'s operational parameters.',
        styles['BulletTaaS']
    ))
    story.append(Paragraph(
        '<b>Asset Security</b>: Because VVU retains full ownership, the hardware cannot be seized, '
        'lien-attached, or otherwise encumbered by municipal financial distress. In the event of client '
        'default or contract termination, VVU exercises its unilateral recovery right to physically '
        'extract and redeploy the assembly at a new service location. This structural protection '
        'transforms the hardware from a sunk-cost risk into a mobile, redeployable commercial asset.',
        styles['BulletTaaS']
    ))
    story.append(Paragraph(
        '<b>Capital Efficiency Rights</b>: The 100% equity position grants VVU the exclusive right '
        'to retrieve and redeploy HBK Mk-II assets across successive service engagements. A terminal '
        'deployed at Municipality A can, upon contract conclusion, be recovered, refurbished, and '
        'redeployed at Municipality B—transforming each hardware unit from a single-deployment cost '
        'center into a multi-lifecycle revenue generator. This capital efficiency model dramatically '
        'reduces per-deployment amortization and accelerates the path to positive unit economics.',
        styles['BulletTaaS']
    ))

    story.append(add_heading('2.2 Sole Data Sovereignty', styles['H2'], level=1))
    story.append(Paragraph(
        'Under the TaaS framework, VVU holds exclusive and non-shareable sovereignty over all data '
        'generated by the deployed HBK Mk-II terminal. The Observation Vector (O_t) comprises four '
        'primary measurement dimensions: <b>P</b> (Pressure), <b>F</b> (Flow), <b>A</b> (Acoustic '
        'signature), and <b>T</b> (Temperature). These four dimensions constitute the raw intelligence '
        'feed from which VVU\'s Bayesian inference engine derives probabilistic leak-localization '
        'outputs. No client, academic partner, or third-party vendor may access, replicate, or '
        'redistribute this data without VVU\'s explicit written authorization.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'The sovereignty framework is enforced through <b>Data-Audit Inseparability</b>: every '
        'Observation Vector packet is cryptographically bound to its generating terminal via SHA-256 '
        'hash chaining. This creates an immutable audit trail that ensures data provenance, integrity, '
        'and non-tampering. The hash chain links each data point to its specific terminal identity, '
        'deployment timestamp, and sensor calibration state—making it impossible to detach data from '
        'its originating context. Furthermore, <b>IP Protection</b> is inherent in the sovereignty '
        'model: the Bayesian inference algorithms, probabilistic models, and localization methodologies '
        'that transform raw O_t data into actionable intelligence are VVU\'s proprietary intellectual '
        'property. The data sovereignty framework ensures that these IP assets cannot be reverse-engineered '
        'or exfiltrated through data access.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('2.3 InfrastructureRight Abstraction', styles['H2'], level=1))
    story.append(Paragraph(
        'The TaaS framework introduces the InfrastructureRight Abstraction—a four-pillar resource '
        'interface that transforms physical infrastructure access into digital rights within a pooled '
        'resource interface. The four pillars are: <b>Water</b> (hydraulic access and flow measurement '
        'rights), <b>Energy</b> (power supply and backup entitlements), <b>Compute</b> (Bayesian '
        'inference processing allocation), and <b>Storage</b> (telemetry data retention and archival '
        'capacity). Each pillar is defined as a quantifiable, contractually guaranteed service level '
        'that the municipality receives as part of its TaaS subscription.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'This abstraction serves a critical architectural purpose: it decouples the client\'s '
        'infrastructure requirements from the specific hardware implementation. The municipality '
        'does not purchase "a pressure sensor" or "a flow meter"—it subscribes to a Water Right '
        'that guarantees a defined level of hydraulic intelligence delivery. If VVU upgrades the '
        'sensor array, replaces a component, or reconfigures the inference pipeline, the client\'s '
        'service level remains constant—the InfrastructureRight is hardware-agnostic. This design '
        'ensures that VVU can continuously improve the terminal\'s capabilities without triggering '
        'contract renegotiations or client-facing configuration changes.',
        styles['BodyTaaS']
    ))

    # ════════════════════════════════════════════════════════
    # SECTION 3: Financial Model & Revenue Distribution
    # ════════════════════════════════════════════════════════
    story.append(CondPageBreak(PAGE_HEIGHT * 0.25))
    story.append(add_heading('3. Financial Model & Revenue Distribution', styles['H1'], level=0))
    story.append(GoldRule(CONTENT_WIDTH))
    story.append(Spacer(1, 6))

    story.append(add_heading('3.1 Subscription-Based OpEx Structure', styles['H2'], level=1))
    story.append(Paragraph(
        'The TaaS financial model is built on a recurring operational expense (OpEx) subscription '
        'structure that replaces the traditional capital expenditure (CapEx) procurement cycle. Under '
        'this model, the municipality pays a fixed monthly or quarterly subscription fee that covers '
        'three bundled service components: <b>Hardware Leasing</b> (the physical HBK Mk-II assembly '
        'deployment and maintenance), <b>Bayesian Inference Services</b> (the probabilistic '
        'leak-localization processing that transforms raw sensor data into actionable intelligence), '
        'and <b>Operational Maintenance</b> (ongoing calibration, component replacement, and firmware '
        'updates). The subscription fee is structured as a fixed operational cost with defined escalation '
        'caps, ensuring budget predictability for the municipality across the contract lifecycle.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'This OpEx structure delivers immediate commercial advantages: the municipality avoids the '
        'large upfront capital outlay that typically requires multi-year budget approval cycles, '
        'VVU gains predictable recurring revenue that supports long-term R&D investment, and the '
        'performance-linked nature of the subscription ensures that VVU\'s revenue is contingent '
        'on delivering measurable infrastructure intelligence rather than merely deploying hardware. '
        'The subscription model also enables flexible scaling—municipalities can adjust their '
        'InfrastructureRight allocations (additional Compute, expanded Storage, enhanced Water '
        'measurement density) within the subscription framework without renegotiating the core contract.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('3.2 The 60/30/10 Revenue Split', styles['H2'], level=1))
    story.append(Paragraph(
        'All TaaS subscription revenue is distributed according to a fixed 60/30/10 allocation model '
        'that balances operational sustainability, growth investment, and risk governance. This split '
        'is contractually fixed and cannot be modified without triparty agreement (VVU, Academic Leads, '
        'Municipal Client) as defined in Section 4.1.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 8))

    # ── Revenue Split Table ──
    revenue_data = [
        [Paragraph('<b>Allocation</b>', styles['TH']),
         Paragraph('<b>Percentage</b>', styles['TH']),
         Paragraph('<b>Scope</b>', styles['TH']),
         Paragraph('<b>Description</b>', styles['TH'])],
        [Paragraph('Operational Baseline', styles['TC']),
         Paragraph('60%', styles['TCC']),
         Paragraph('Hardware + Operations', styles['TC']),
         Paragraph('Hardware amortization, server costs, HBK inference engine maintenance, field service operations', styles['TC'])],
        [Paragraph('Growth & R&D', styles['TC']),
         Paragraph('30%', styles['TCC']),
         Paragraph('Software + Research', styles['TC']),
         Paragraph('Software refinement, Bayesian algorithm improvement, academic collaboration funding, next-generation terminal development', styles['TC'])],
        [Paragraph('Risk & Compliance', styles['TC']),
         Paragraph('10%', styles['TCC']),
         Paragraph('Audit + Regulatory', styles['TC']),
         Paragraph('ProofBridge-Liner audit chain operations, regulatory alignment, SRS parameter verification, compliance documentation', styles['TC'])],
    ]

    rev_col_widths = [CONTENT_WIDTH * 0.18, CONTENT_WIDTH * 0.12,
                      CONTENT_WIDTH * 0.20, CONTENT_WIDTH * 0.50]

    revenue_table = Table(revenue_data, colWidths=rev_col_widths, repeatRows=1)
    revenue_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(revenue_table)
    story.append(Spacer(1, 8))

    story.append(add_heading('3.3 Incentive Alignment', styles['H2'], level=1))
    story.append(Paragraph(
        'The 30% Growth & R&D allocation is not merely a cost center—it is the incentive alignment '
        'mechanism that ensures continuous improvement in the terminal\'s leak-localization accuracy. '
        'Under the TaaS SLA framework (Section 5), VVU commits to achieving a search radius of '
        '500 meters or less for leak localization. The 30% R&D allocation funds the Bayesian '
        'algorithm refinement, academic research partnerships, and next-generation sensor development '
        'that continuously narrow the search radius toward this target. This creates a self-reinforcing '
        'commercial cycle: improved accuracy increases client satisfaction and contract renewal rates, '
        'which in turn generates additional subscription revenue that funds further R&D investment. '
        'The 60/30/10 split ensures that this cycle is structurally financed—not dependent on ad hoc '
        'budget allocations or external grant funding.',
        styles['BodyTaaS']
    ))

    # ════════════════════════════════════════════════════════
    # SECTION 4: Risk Mitigation & "Zero Fabrication" Governance
    # ════════════════════════════════════════════════════════
    story.append(CondPageBreak(PAGE_HEIGHT * 0.25))
    story.append(add_heading('4. Risk Mitigation & "Zero Fabrication" Governance', styles['H1'], level=0))
    story.append(GoldRule(CONTENT_WIDTH))
    story.append(Spacer(1, 6))

    story.append(add_heading('4.1 Administrative Shielding — Triparty SRS Delegation', styles['H2'], level=1))
    story.append(Paragraph(
        'The TaaS governance framework implements a Triparty SRS (System Requirements Specification) '
        'Delegation Addendum known as the "Three Keys" mechanism. Under this governance structure, '
        'no single party can unilaterally modify, waive, or bypass any SRS parameter. The three '
        'keyholders are: <b>VVU</b> (the service provider and hardware owner), <b>Academic Leads</b> '
        '(the independent research validators), and <b>Municipal Client</b> (the service subscriber '
        'and infrastructure operator). Any modification to the SRS requires simultaneous authorization '
        'from all three keyholders, ensuring that commercial pressures from VVU, research ambitions '
        'from academic partners, or operational convenience from the municipality cannot individually '
        'compromise the terminal\'s safety and performance parameters.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'This administrative shielding is particularly critical in the context of the Zero Fabrication '
        'Mandate (Section 4.2). The Three Keys mechanism ensures that no manufacturing funds can be '
        'released, no SRS parameter can be relaxed, and no deployment can proceed without triparty '
        'consensus. The governance structure transforms the SRS from a unilateral specification into '
        'a multilateral contract—protecting all parties from the consequences of premature or '
        'under-specified hardware production.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('4.2 Zero Fabrication Mandate', styles['H2'], level=1))
    story.append(Paragraph(
        'The Zero Fabrication Mandate is the foundational risk governance principle of the TaaS '
        'framework: no manufacturing funds shall be released until all 32 SRS parameters have been '
        'verified and validated. This mandate exists to prevent the most catastrophic failure mode '
        'in infrastructure hardware production—manufacturing a terminal that has not been fully '
        'specified, tested, and certified. The 32 SRS parameters encompass every dimension of the '
        'terminal\'s operational specification: hydraulic performance, structural integrity, '
        'electromagnetic compatibility, environmental resilience, and Bayesian inference accuracy.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 8))

    # ── Safe Harbor Boundaries Table ──
    safe_harbor_data = [
        [Paragraph('<b>Parameter</b>', styles['TH']),
         Paragraph('<b>Boundary Value</b>', styles['TH']),
         Paragraph('<b>Unit</b>', styles['TH']),
         Paragraph('<b>Governance Scope</b>', styles['TH'])],
        [Paragraph('Surge Maximum', styles['TC']),
         Paragraph('20', styles['TCC']),
         Paragraph('bar', styles['TCC']),
         Paragraph('Hydraulic pressure safety ceiling — no deployment above this threshold', styles['TC'])],
        [Paragraph('Wave Celerity', styles['TC']),
         Paragraph('1400', styles['TCC']),
         Paragraph('m/s', styles['TCC']),
         Paragraph('Acoustic propagation speed limit for Bayesian inference calibration', styles['TC'])],
        [Paragraph('Corrosion Limit', styles['TC']),
         Paragraph('10.00', styles['TCC']),
         Paragraph('mm', styles['TCC']),
         Paragraph('Maximum permissible material degradation before mandatory component replacement', styles['TC'])],
        [Paragraph('Structural Bound (FoS)', styles['TC']),
         Paragraph('1.5 - 3.0', styles['TCC']),
         Paragraph('ratio', styles['TCC']),
         Paragraph('Factor of Safety range for structural load-bearing components under all operating conditions', styles['TC'])],
    ]

    sh_col_widths = [CONTENT_WIDTH * 0.18, CONTENT_WIDTH * 0.12,
                     CONTENT_WIDTH * 0.08, CONTENT_WIDTH * 0.62]

    safe_harbor_table = Table(safe_harbor_data, colWidths=sh_col_widths, repeatRows=1)
    safe_harbor_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(safe_harbor_table)
    story.append(Spacer(1, 8))

    story.append(add_heading('4.3 Verification Gates VR1-VR5', styles['H2'], level=1))
    story.append(Paragraph(
        'The Zero Fabrication Mandate is enforced through a five-stage verification gate system '
        'that progressively validates the terminal from geometric specification through field '
        'acceptance. Each gate represents a mandatory checkpoint that must be passed before the '
        'next stage can proceed. No gate may be skipped, combined, or conditionally waived. The '
        'verification gates establish a linear, non-parallel validation path that ensures every '
        'dimension of the terminal\'s specification is independently confirmed.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 8))

    # ── Verification Gates Table ──
    gate_data = [
        [Paragraph('<b>Gate</b>', styles['TH']),
         Paragraph('<b>Designation</b>', styles['TH']),
         Paragraph('<b>Scope</b>', styles['TH']),
         Paragraph('<b>Validation Criteria</b>', styles['TH'])],
        [Paragraph('VR1', styles['TCC']),
         Paragraph('Geometry', styles['TC']),
         Paragraph('Physical dimensions and spatial layout', styles['TC']),
         Paragraph('All 11 component XYZ positions verified against SRS coordinate specification', styles['TC'])],
        [Paragraph('VR2', styles['TCC']),
         Paragraph('Material', styles['TC']),
         Paragraph('Material composition and properties', styles['TC']),
         Paragraph('Material certificates, corrosion resistance testing, and structural strength validation', styles['TC'])],
        [Paragraph('VR3', styles['TCC']),
         Paragraph('Assembly', styles['TC']),
         Paragraph('Component integration and coupling', styles['TC']),
         Paragraph('Inter-component connectivity, hydraulic seal integrity, and electrical bonding verification', styles['TC'])],
        [Paragraph('VR4', styles['TCC']),
         Paragraph('Functional (FAT)', styles['TC']),
         Paragraph('Factory Acceptance Testing', styles['TC']),
         Paragraph('Full functional testing under simulated operational conditions, Bayesian inference output validation', styles['TC'])],
        [Paragraph('VR5', styles['TCC']),
         Paragraph('Field Acceptance (SAT)', styles['TC']),
         Paragraph('Site Acceptance Testing', styles['TC']),
         Paragraph('In-situ performance validation at deployment site, live hydraulic conditions, telemetry confirmation', styles['TC'])],
    ]

    gate_col_widths = [CONTENT_WIDTH * 0.08, CONTENT_WIDTH * 0.14,
                       CONTENT_WIDTH * 0.28, CONTENT_WIDTH * 0.50]

    gate_table = Table(gate_data, colWidths=gate_col_widths, repeatRows=1)
    gate_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 4), (-1, 4), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 5), (-1, 5), TABLE_ROW_EVEN),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(gate_table)
    story.append(Spacer(1, 8))

    # ════════════════════════════════════════════════════════
    # SECTION 5: Operational Performance Targets (SLA Metrics)
    # ════════════════════════════════════════════════════════
    story.append(CondPageBreak(PAGE_HEIGHT * 0.25))
    story.append(add_heading('5. Operational Performance Targets (SLA Metrics)', styles['H1'], level=0))
    story.append(GoldRule(CONTENT_WIDTH))
    story.append(Spacer(1, 6))

    story.append(add_heading('5.1 Leak Localization Accuracy', styles['H2'], level=1))
    story.append(Paragraph(
        'The primary SLA metric for the TaaS framework is leak localization accuracy, measured as '
        'the reduction in search uncertainty relative to conventional detection methods. The HBK Mk-II '
        'terminal, operating under its Bayesian inference engine, commits to achieving a <b>95% '
        'reduction in search uncertainty</b> compared to traditional acoustic correlation methods. '
        'This translates to a <b>maximum search radius of 500 meters</b> for any detected leak event. '
        'The search radius metric is the most operationally significant performance indicator: it '
        'defines the physical area that municipal repair teams must inspect to locate the leak source. '
        'A 500-meter search radius means that excavation and repair resources can be deployed with '
        'precision rather than dispersed across kilometers of pipeline infrastructure.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'The accuracy target is achieved through the convergence of three technical capabilities: '
        'the Observation Vector\'s four-dimensional sensor data (P, F, A, T), the Bayesian inference '
        'engine\'s probabilistic spatial mapping, and the SHA-256 hash-chained data integrity that '
        'ensures no sensor drift or data corruption degrades the localization output. The 95% '
        'reduction target is not a static benchmark—it is a continuously improving metric driven by '
        'the 30% R&D revenue allocation that funds ongoing algorithm refinement and sensor calibration '
        'research.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('5.2 False-Positive Suppression', styles['H2'], level=1))
    story.append(Paragraph(
        'False-positive events represent the most costly failure mode in leak detection operations: '
        'each false alarm triggers unnecessary excavation, pipeline shutdown, and resource deployment '
        'that wastes municipal operational budget and erodes confidence in the detection system. The '
        'TaaS SLA framework addresses this through a strict <b>False-Positive Rate (FPR) target of '
        '5% or less</b>, enforced via Poisson-Gaussian mixture distributions in the Bayesian inference '
        'engine. The Poisson component models the discrete event frequency (how many leak events occur '
        'in a given observation window), while the Gaussian component models the continuous measurement '
        'noise (sensor signal variability under normal operating conditions). The mixture distribution '
        'enables the inference engine to distinguish between genuine hydraulic anomalies (actual leaks) '
        'and statistical noise fluctuations (false triggers) with high confidence.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'The 5% FPR target is validated against historical pipeline data from comparable municipal '
        'networks and is subject to continuous recalibration as the terminal accumulates site-specific '
        'operational data. Each false-positive event is logged, analyzed, and fed back into the '
        'inference engine\'s training dataset—ensuring that the FPR metric improves over the '
        'deployment lifecycle rather than degrading.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('5.3 Information Density Guarantee', styles['H2'], level=1))
    story.append(Paragraph(
        'The Information Density (ID) metric is the ultimate efficiency indicator for the TaaS '
        'framework, defined as: <b>ID = Information Gained / Deployment Cost</b>. This ratio '
        'measures the operational intelligence yield per unit of financial investment. Unlike raw '
        'accuracy metrics that measure detection performance in isolation, Information Density '
        'contextualizes performance within the commercial framework—ensuring that the intelligence '
        'delivery is not merely accurate but economically efficient.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'The ID metric serves two governance functions. First, it provides the Municipal Client with '
        'a quantifiable return-on-investment indicator: each subscription payment can be evaluated '
        'against the volume and precision of infrastructure intelligence received. Second, it provides '
        'VVU with an internal efficiency benchmark: if the ID ratio declines (indicating that '
        'deployment costs are rising faster than intelligence yield), the 30% R&D allocation is '
        'directed toward the specific technical bottlenecks—sensor calibration, algorithm refinement, '
        'or hardware optimization—that are degrading the ratio.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 8))

    # ── SLA Metrics Table ──
    sla_data = [
        [Paragraph('<b>SLA Metric</b>', styles['TH']),
         Paragraph('<b>Target</b>', styles['TH']),
         Paragraph('<b>Measurement Method</b>', styles['TH']),
         Paragraph('<b>Governance Mechanism</b>', styles['TH'])],
        [Paragraph('Leak Localization Accuracy', styles['TC']),
         Paragraph('95% reduction / 500m radius', styles['TC']),
         Paragraph('Bayesian inference spatial probability mapping', styles['TC']),
         Paragraph('30% R&D allocation for continuous algorithm refinement', styles['TC'])],
        [Paragraph('False-Positive Rate', styles['TC']),
         Paragraph('5% or less', styles['TC']),
         Paragraph('Poisson-Gaussian mixture distribution analysis', styles['TC']),
         Paragraph('Continuous recalibration against site-specific operational data', styles['TC'])],
        [Paragraph('Information Density', styles['TC']),
         Paragraph('ID = Info Gained / Deploy Cost', styles['TC']),
         Paragraph('Ratio of intelligence yield to subscription investment', styles['TC']),
         Paragraph('Internal efficiency benchmark driving R&D priority allocation', styles['TC'])],
    ]

    sla_col_widths = [CONTENT_WIDTH * 0.20, CONTENT_WIDTH * 0.18,
                      CONTENT_WIDTH * 0.30, CONTENT_WIDTH * 0.32]

    sla_table = Table(sla_data, colWidths=sla_col_widths, repeatRows=1)
    sla_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
        ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
        ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
    ]))
    story.append(sla_table)

    # ════════════════════════════════════════════════════════
    # SECTION 6: Vendor Financing Terms
    # ════════════════════════════════════════════════════════
    story.append(CondPageBreak(PAGE_HEIGHT * 0.25))
    story.append(add_heading('6. Vendor Financing Terms', styles['H1'], level=0))
    story.append(GoldRule(CONTENT_WIDTH))
    story.append(Spacer(1, 6))

    story.append(add_heading('6.1 Tooling Deposit — Tranche 1 Budget Lock', styles['H2'], level=1))
    story.append(Paragraph(
        'The TaaS vendor financing framework establishes a structured capital release mechanism '
        'that enforces the Zero Fabrication Mandate at the financial level. The <b>Tranche 1 Budget '
        'Lock</b> of <b>R812,490.00</b> is a ring-fenced tooling deposit that covers the production '
        'mold fabrication and the KCL (Kinematic Calibration Library) parametric library development. '
        'This deposit is released only upon successful completion of Verification Gate VR1 (Geometry) '
        'and VR2 (Material)—ensuring that no manufacturing capital is deployed before the terminal\'s '
        'physical and material specifications have been independently validated by the triparty '
        'keyholder structure.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'The Tranche 1 deposit structure serves two protective functions. First, it ensures that VVU\'s '
        'manufacturing investment is preceded by validated specifications—preventing the costly scenario '
        'of producing molds against unverified or incomplete SRS parameters. Second, it provides the '
        'fabrication partner with a committed capital baseline that enables production planning without '
        'financial uncertainty. The Budget Lock is non-revocable once released: VVU cannot retract the '
        'tooling deposit after VR1/VR2 completion, providing the fabrication partner with contractual '
        'assurance that their production investment will be honored.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('6.2 Prototyping Exemptions — Limited Experimental Validation Builds', styles['H2'], level=1))
    story.append(Paragraph(
        'While the Zero Fabrication Mandate prohibits production manufacturing before full SRS '
        'verification, the framework recognizes the necessity of limited experimental validation '
        'builds for testing and calibration purposes. The <b>Prototyping Exemptions</b> clause '
        'permits fractional, ring-fenced capital releases for Limited Experimental Validation Builds—'
        'small-scale production runs (typically 1-3 units) intended solely for laboratory testing, '
        'Bayesian inference calibration, and field simulation exercises. These exemption builds are '
        'strictly governed: they may not be deployed at client sites, they may not be sold or '
        'transferred, and they must be decommissioned after their validation lifecycle concludes.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'The prototyping exemption framework ensures that VVU can validate the terminal\'s inference '
        'accuracy, sensor calibration, and hydraulic performance under controlled conditions without '
        'violating the Zero Fabrication principle. The exemption builds are funded from the 30% '
        'R&D allocation—not from the Tranche 1 tooling deposit—ensuring that production capital and '
        'validation capital are financially separated. This separation prevents the common failure mode '
        'where prototyping costs erode production budgets, forcing manufacturing compromises that '
        'degrade the final product.',
        styles['BodyTaaS']
    ))

    story.append(add_heading('6.3 Default & Asset Recovery', styles['H2'], level=1))
    story.append(Paragraph(
        'The default and asset recovery framework is the ultimate enforcement mechanism of VVU\'s '
        '100% equity retention principle. In the event of client default—whether through subscription '
        'payment failure, contract violation, or operational non-compliance—VVU exercises its '
        '<b>unilateral right to recover and redeploy HBK Mk-II assets</b>. This right is absolute '
        'and non-negotiable: no client agreement, municipal regulation, or third-party claim may '
        'prevent VVU from physically extracting the deployed terminal and relocating it to a new '
        'service engagement.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'The recovery framework operates under a defined procedural sequence. Upon default event '
        'confirmation, VVU issues a formal Recovery Notice to the Municipal Client with a 30-day '
        'compliance window. If the default is not remediated within this window, VVU dispatches a '
        'field recovery team to decommission and extract the terminal assembly. The recovered asset '
        'enters VVU\'s refurbishment pipeline: components are inspected, recalibrated, and upgraded '
        'as necessary before redeployment at a subsequent service location. The recovery cost is '
        'absorbed by VVU\'s 10% Risk & Compliance allocation—ensuring that asset recovery does not '
        'impose additional financial burden on the Operational Baseline or R&D budget lines.',
        styles['BodyTaaS']
    ))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        'This recovery mechanism transforms the TaaS model from a rental arrangement into a true '
        'service lifecycle: the hardware is never "sold and forgotten" but remains a perpetually '
        'managed commercial asset that generates revenue across multiple deployment cycles. The '
        'unilateral recovery right ensures that VVU\'s capital investment in each HBK Mk-II unit '
        'is protected regardless of individual client outcomes—de-risking the overall portfolio '
        'and enabling confident investment in next-generation terminal development.',
        styles['BodyTaaS']
    ))

    # ── End of document marker ──
    story.append(Spacer(1, 16))
    story.append(SectionDivider(CONTENT_WIDTH, 'VVU-TaaS-CFS-2026-001 — END OF SPECIFICATION'))

    return story


# ─── Main ───
def main():
    styles = create_styles()

    # Define frame
    frame = Frame(
        LEFT_MARGIN, BOTTOM_MARGIN,
        CONTENT_WIDTH, PAGE_HEIGHT - TOP_MARGIN - BOTTOM_MARGIN,
        id='body_frame'
    )

    # Page template with Arabic footer
    body_template = PageTemplate(
        id='body',
        frames=[frame],
        onPage=footer_arabic,
    )

    # Build document with custom template as default
    doc = TocDocTemplate(
        OUTPUT_PATH,
        pagesize=A4,
        title='VVU HBK Mk-II Terminal-as-a-Service (TaaS) Commercial Framework Specification',
        author='VVU EARTH TECH',
        subject='Commercial Framework Specification for TaaS Deployment',
        creator='ReportLab via VVU Document Pipeline',
    )

    # Add the body template with footer — this becomes the only template
    doc.addPageTemplates([body_template])

    story = build_story(styles)
    doc.multiBuild(story)

    print(f'Body PDF generated: {OUTPUT_PATH}')


if __name__ == '__main__':
    main()
