import { NextRequest, NextResponse } from "next/server";

// GET /api/shards?policyId=... — list shards (mock data)
export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const policyId = searchParams.get("policyId");

  const allShards = [
    // grid_frequency_stability shards
    { id: "sh-1", policyId: "pol-1", shardKey: "geo_region", region: "europe-west", nodeId: "edge-01", state: '{"frequency":50.01,"generation":[420,380,510],"load":[410,375,500],"losses":12,"thermal_headroom":18,"geo_region":"europe-west"}', invariantStatus: "healthy", mmrRoot: "mmr_root_abc", peerCount: 3, lastMergeAt: "2025-06-01T00:00:00Z", createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "grid_frequency_stability", domain: "smart_grid" }, invariantEvals: [{ name: "freq_bounds", passed: true, severity: "critical", soft: false }, { name: "energy_conservation", passed: true, severity: "critical", soft: false }, { name: "thermal_headroom", passed: true, severity: "medium", soft: true }] },
    { id: "sh-2", policyId: "pol-1", shardKey: "geo_region", region: "europe-north", nodeId: "edge-02", state: '{"frequency":49.95,"generation":[380,290,600],"load":[375,285,590],"losses":10,"thermal_headroom":6,"geo_region":"europe-north"}', invariantStatus: "violating", mmrRoot: "mmr_root_def", peerCount: 2, lastMergeAt: "2025-06-01T00:00:00Z", createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "grid_frequency_stability", domain: "smart_grid" }, invariantEvals: [{ name: "freq_bounds", passed: false, severity: "critical", soft: false }, { name: "energy_conservation", passed: true, severity: "critical", soft: false }, { name: "thermal_headroom", passed: false, severity: "medium", soft: true }] },
    { id: "sh-3", policyId: "pol-1", shardKey: "geo_region", region: "na-east", nodeId: "edge-03", state: '{"frequency":50.05,"generation":[510,470,290],"load":[500,460,285],"losses":14,"thermal_headroom":22,"geo_region":"na-east"}', invariantStatus: "repairing", mmrRoot: "mmr_root_ghi", peerCount: 4, lastMergeAt: null, createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "grid_frequency_stability", domain: "smart_grid" }, invariantEvals: [{ name: "freq_bounds", passed: true, severity: "critical", soft: false }, { name: "energy_conservation", passed: true, severity: "critical", soft: false }, { name: "thermal_headroom", passed: true, severity: "medium", soft: true }] },
    // fleet_safety_envelope shards
    { id: "sh-4", policyId: "pol-3", shardKey: "vehicle_id", region: "apac-south", nodeId: "cloud-01", state: '{"vehicle_id":"AV-042","separation":[3.2,2.8,4.1,2.5,5.0],"speed":64,"braking_budget":42,"jerk":-1.8}', invariantStatus: "healthy", mmrRoot: "mmr_root_fleet1", peerCount: 3, lastMergeAt: "2025-06-01T00:00:00Z", createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "fleet_safety_envelope", domain: "autonomous_vehicles" }, invariantEvals: [{ name: "min_separation", passed: true, severity: "critical", soft: false }, { name: "speed_bound", passed: true, severity: "critical", soft: false }, { name: "braking_energy", passed: true, severity: "high", soft: false }, { name: "comfort_jerk", passed: true, severity: "low", soft: true }] },
    { id: "sh-5", policyId: "pol-3", shardKey: "vehicle_id", region: "apac-east", nodeId: "cloud-02", state: '{"vehicle_id":"AV-004","separation":[1.2,2.8,4.1,2.5,5.0],"speed":134,"braking_budget":-8,"jerk":-3.4}', invariantStatus: "violating", mmrRoot: "mmr_root_fleet2", peerCount: 2, lastMergeAt: null, createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "fleet_safety_envelope", domain: "autonomous_vehicles" }, invariantEvals: [{ name: "min_separation", passed: false, severity: "critical", soft: false }, { name: "speed_bound", passed: false, severity: "critical", soft: false }, { name: "braking_energy", passed: false, severity: "high", soft: false }, { name: "comfort_jerk", passed: false, severity: "low", soft: true }] },
    // cold_chain_integrity shards
    { id: "sh-6", policyId: "pol-4", shardKey: "custody_stage", region: "europe-west", nodeId: "edge-01", state: '{"custody_stage":"producer","temperature":4.5,"excursion_minutes":8,"humidity":48}', invariantStatus: "healthy", mmrRoot: "mmr_root_cc1", peerCount: 2, lastMergeAt: null, createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "cold_chain_integrity", domain: "supply_chain" }, invariantEvals: [{ name: "temp_range", passed: true, severity: "critical", soft: false }, { name: "excursion_dose", passed: true, severity: "high", soft: false }, { name: "humidity_range", passed: true, severity: "low", soft: true }] },
    { id: "sh-7", policyId: "pol-4", shardKey: "custody_stage", region: "europe-north", nodeId: "edge-02", state: '{"custody_stage":"transporter","temperature":5.2,"excursion_minutes":12,"humidity":38}', invariantStatus: "healthy", mmrRoot: "mmr_root_cc2", peerCount: 3, lastMergeAt: null, createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "cold_chain_integrity", domain: "supply_chain" }, invariantEvals: [{ name: "temp_range", passed: true, severity: "critical", soft: false }, { name: "excursion_dose", passed: true, severity: "high", soft: false }, { name: "humidity_range", passed: true, severity: "low", soft: true }] },
    // water_treatment_safety shards
    { id: "sh-8", policyId: "pol-6", shardKey: "plant_unit", region: "europe-west", nodeId: "edge-01", state: '{"plant_unit":"plant-north","chlorine_residual":1.8,"ph":7.2,"main_pressure":6.4,"turbidity":0.4}', invariantStatus: "healthy", mmrRoot: "mmr_root_wt1", peerCount: 3, lastMergeAt: "2025-06-01T00:00:00Z", createdAt: "2025-01-01T00:00:00Z", updatedAt: "2025-06-01T00:00:00Z", policy: { name: "water_treatment_safety", domain: "water_utility" }, invariantEvals: [{ name: "chlorine_residual", passed: true, severity: "critical", soft: false }, { name: "ph_range", passed: true, severity: "critical", soft: false }, { name: "main_pressure", passed: true, severity: "critical", soft: false }, { name: "turbidity", passed: true, severity: "medium", soft: true }] },
  ];

  const shards = policyId
    ? allShards.filter((s) => s.policyId === policyId)
    : allShards;

  return NextResponse.json({ shards });
}
