import { NextResponse } from 'next/server';

export async function GET() {
  try {
    const data = {
      migrationFacts: [
        {
          id: 'mig-001',
          type: 'migration_planned',
          fromVersion: '0.7',
          toVersion: '0.8',
          environment: 'production',
          component: 'core',
          reason: 'Acceptance Engine integration',
          timestamp: '2026-01-15T10:00:00Z',
          status: 'accepted',
        },
        {
          id: 'mig-002',
          type: 'migration_checkpoint_reached',
          fromVersion: '0.7',
          toVersion: '0.8',
          environment: 'production',
          component: 'schema',
          stepId: 'step-1',
          timestamp: '2026-01-15T10:15:00Z',
          status: 'accepted',
        },
        {
          id: 'mig-003',
          type: 'migration_checkpoint_reached',
          fromVersion: '0.7',
          toVersion: '0.8',
          environment: 'production',
          component: 'policy',
          stepId: 'step-2',
          timestamp: '2026-01-15T10:30:00Z',
          status: 'accepted',
        },
        {
          id: 'mig-004',
          type: 'migration_verified',
          fromVersion: '0.7',
          toVersion: '0.8',
          environment: 'production',
          component: 'core',
          checks: { schema: true, policy: true, projection: true, ordering: true },
          timestamp: '2026-01-15T10:45:00Z',
          status: 'accepted',
        },
        {
          id: 'mig-005',
          type: 'migration_completed',
          fromVersion: '0.7',
          toVersion: '0.8',
          environment: 'production',
          component: 'core',
          timestamp: '2026-01-15T11:00:00Z',
          status: 'accepted',
        },
        {
          id: 'mig-006',
          type: 'migration_planned',
          fromVersion: '0.8',
          toVersion: '0.9',
          environment: 'staging',
          component: 'consensus',
          reason: 'Distributed consensus adapter',
          timestamp: '2026-01-16T09:00:00Z',
          status: 'accepted',
        },
        {
          id: 'mig-007',
          type: 'migration_failed',
          fromVersion: '0.8',
          toVersion: '0.9',
          environment: 'staging',
          component: 'consensus',
          reason: 'Schema conflict in consensus adapter',
          stepId: 'step-1',
          recoverable: false,
          timestamp: '2026-01-16T09:10:00Z',
          status: 'accepted',
        },
        {
          id: 'mig-008',
          type: 'migration_rolled_back',
          fromVersion: '0.8',
          toVersion: '0.9',
          environment: 'staging',
          component: 'consensus',
          reason: 'Policy violation during consensus migration',
          timestamp: '2026-01-13T14:00:00Z',
          status: 'accepted',
        },
      ],
      failureFacts: [
        {
          id: 'fail-001',
          type: 'migration_failed',
          reason: 'Schema conflict in consensus adapter',
          parentFactId: 'mig-007',
          stepId: 'step-1',
          errorDetails: "Field 'consensusType' not found in schema v0.8",
          recoverable: false,
          timestamp: '2026-01-16T09:10:00Z',
        },
        {
          id: 'fail-002',
          type: 'migration_failed',
          reason: 'Timeout on shard rebalance',
          parentFactId: 'mig-003',
          stepId: 'step-3',
          errorDetails: 'Shard rebalance exceeded 30s timeout',
          recoverable: true,
          timestamp: '2026-01-11T16:00:00Z',
        },
        {
          id: 'fail-003',
          type: 'migration_rolled_back',
          reason: 'Policy violation during consensus migration',
          parentFactId: 'mig-008',
          stepId: 'step-2',
          errorDetails: "Policy 'consensus-adapter-v1' not found",
          recoverable: false,
          timestamp: '2026-01-13T14:00:00Z',
        },
      ],
      projections: [
        {
          id: 'proj-001',
          projectionId: 'dashboard-v1',
          version: '1.2.0',
          schema: 'projection-dashboard/v1',
          effectiveFrom: '2025-06-01T00:00:00Z',
          status: 'active',
        },
        {
          id: 'proj-002',
          projectionId: 'audit-trail-v1',
          version: '1.0.0',
          schema: 'projection-audit/v1',
          effectiveFrom: '2025-06-01T00:00:00Z',
          status: 'active',
        },
        {
          id: 'proj-003',
          projectionId: 'trust-score-v1',
          version: '2.1.0',
          schema: 'projection-trust/v2',
          effectiveFrom: '2025-09-15T00:00:00Z',
          status: 'active',
        },
        {
          id: 'proj-004',
          projectionId: 'migration-status-v1',
          version: '1.0.0',
          schema: 'projection-migration/v1',
          effectiveFrom: '2026-01-15T00:00:00Z',
          status: 'active',
        },
        {
          id: 'proj-005',
          projectionId: 'previous-dashboard-v0',
          version: '0.9.0',
          schema: 'projection-dashboard/v0',
          effectiveFrom: '2025-01-01T00:00:00Z',
          status: 'deprecated',
          deprecatedAt: '2025-09-15T00:00:00Z',
          reason: 'Replaced by dashboard-v1 with policy time-travel support',
        },
      ],
      policies: [
        {
          id: 'pol-001',
          name: 'migration-policy-v1',
          version: '1.0.0',
          effectiveFrom: '2025-06-01T00:00:00Z',
          effectiveTo: null,
          description: 'Governs migration fact acceptance',
        },
        {
          id: 'pol-002',
          name: 'migration-policy-v2',
          version: '2.0.0',
          effectiveFrom: '2026-01-15T00:00:00Z',
          effectiveTo: null,
          description: 'Enhanced migration policy with time-travel',
        },
        {
          id: 'pol-003',
          name: 'previous-migration-policy',
          version: '0.9.0',
          effectiveFrom: '2025-01-01T00:00:00Z',
          effectiveTo: '2025-06-01T00:00:00Z',
          description: 'Original migration policy (deprecated)',
        },
      ],
      specAlignment: [
        { requirement: 'Migration as Facts', implementation: 'migration_* Fact types', status: 'aligned' },
        { requirement: 'Failure as Facts', implementation: 'migration_failed Fact', status: 'aligned' },
        { requirement: 'Acceptance Pipeline', implementation: '8-stage pipeline', status: 'required' },
        { requirement: 'Policy Time Travel', implementation: 'Evaluate at fact.acceptedAt', status: 'required' },
        { requirement: 'Projection Versioning', implementation: 'Versioned Projection Facts', status: 'required' },
        { requirement: 'Deterministic Ordering', implementation: 'LogicalSequence', status: 'required' },
        { requirement: 'Canonical Serialization', implementation: 'RFC 8785', status: 'required' },
        { requirement: 'Kernel Never Shells Out', implementation: 'Migration Adapter', status: 'aligned' },
        { requirement: 'Deprecation Not Kernel', implementation: 'No DeprecationEvent', status: 'aligned' },
      ],
      metrics: {
        totalMigrations: 5,
        completedMigrations: 3,
        failedMigrations: 2,
        rollbackRate: 0.4,
        avgMigrationDuration: '45m',
        factsPerMigration: 4.2,
      },
    };

    return NextResponse.json(data, {
      headers: { 'Cache-Control': 'no-store' },
    });
  } catch (error) {
    console.error('Migration API error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch migration data' },
      { status: 500, headers: { 'Cache-Control': 'no-store' } }
    );
  }
}
