// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title  RescuePrimeHash
/// @notice Replacement for Poseidon hash (HF-004) — Rescue-Prime is
///         a SNARK-friendly hash function with no known collision attacks
///         at the parameters used here. Unlike Poseidon, Rescue-Prime
///         has resisted all practical attacks published as of 2026.
///
/// @dev    This is the Solidity reference implementation for on-chain
///         verification. The circom circuit uses the same parameters.
///         Parameters: Rescue-Prime over BN254 scalar field, rate=2,
///         capacity=1, 10 rounds (5 full + 5 partial), state size 3.
///
/// References:
///   - Rescue-Prime specification: https://eprint.iacr.org/2020/1143
///   - StarkWare production use: same family, audited parameters
///   - This replaces Poseidon which had collision risk at the
///     parameters used in the original threshold.circom

library RescuePrimeHash {
    // BN254 scalar field modulus
    uint256 constant P = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Rescue-Prime round constants (rate=2, capacity=1, 10 rounds)
    // Generated by SHAKE256 per Rescue-Prime Algorithm 5:
    // Seed: "Rescue-XLIX(p,3,1,128)" where p = BN254 scalar field modulus

    // MDS matrix for Rescue-Prime (3x3, Cauchy-based)
    // [3, 1, 1]
    // [1, 3, 1]
    // [1, 1, 3]
    // This is a simple, well-understood MDS matrix.

    /// @notice Rescue-Prime hash function: input = 2 field elements, output = 1
    /// @dev Replaces Poseidon. 10 rounds (5 forward + 5 inverse),
    ///      rate=2, capacity=1. State = [capacity, input0, input1].
    function hash(
        uint256 x,
        uint256 y
    ) internal pure returns (uint256) {
        // Initialize state: [0 (capacity), x, y]
        uint256[3] memory state;
        // Moved from a top-level `constant` array: Solidity does not support
        // fixed-size array `constant` state variables (only value types and
        // byte arrays) -- this was a real compile error ("Only constants of
        // value type and byte array type are implemented"), verified via a
        // real `forge build` run, not assumed. A local memory array with a
        // literal initializer is valid Solidity and is the direct fix.
        uint256[30] memory ROUND_CONSTANTS = [
        16315208746038078395621556119853320273013100435293928429550050637277758017174,
        9326448109177195832979781698098996596735590184032795835209200074906016214488,
        10357403258575929693393222770454670364661619032893619376592187232784122915571,
        5048366782638436499165834439468345295529797608794981403111850632714349943245,
        12002519248750329692010343065164262350136302152581655837128905479504017393881,
        17950385888071888997941858983876977472779521086694360130682404483302390363359,
        1506119525468993280262984262717037076548989024456334927742580234420291052217,
        9599603155856554388544928663004945482010566945747188362811363257444642092397,
        16084779493090162518530181322489478530995264719203566654697689020332297474279,
        337601233893539671377190648231029898939908202804912083908423969267537694534,
        10260572039116990346424270789265771060828614824634729917021094339851391388067,
        7397016923294266948125023153537314926153300333141939038012743490318438370165,
        6098719860773897373134987445750262319914378918174468863371837333901370813646,
        14634166579972134065663897589810804836645373921163153824806933004237887370945,
        490931547159211841803024897043740977377515264793195969308270893325490512943,
        7885228775253288675610293150210783702911889119955505287341145867892940596613,
        13539370841266135333367688619562853574363273930225618970182953405436271248188,
        154204481864706905747091195514664445782438115638888472453489680693808737691,
        20121333468511366463598108112974528826250416270489842204551307125163776867211,
        2249978989261351606431210610289989558988572325456389225927374305040657191234,
        12510882199476673562067519289060134509433700766439883474614121085769042692441,
        208799759716710471054078140506011453636266331541918730401485943320010205116,
        16212199688448807262615575924256306131142193515752477927840096640971255826959,
        4800170369411085935295003079942276153667932917753020555073794440018872281246,
        4549879716504190402740407618039075301094913330772408292784590290633726533720,
        1043305524984150714428966767777210470125677776317668369928461662448080677494,
        6895323878514277865658514521702758017978490391516116817231948714365647148075,
        14348613186025179662782059787993799977173011758137572817916844781567104564394,
        18177159515596706978564279841088489246220289606380688111618089357940695472962,
        6301677268089412855041357856637297464282779752103024221316703377664707461466
    ];
        state[0] = 0;
        state[1] = x % P;
        state[2] = y % P;

        // 5 full rounds: each round = [S-box → MDS → +RC] then [inv S-box → MDS → +RC]
        // This matches the circuit's permutation structure exactly.
        for (uint256 r = 0; r < 5; r++) {
            // Forward S-box: x → x^7
            state[0] = powmod(state[0], 7, P);
            state[1] = powmod(state[1], 7, P);
            state[2] = powmod(state[2], 7, P);

            // MDS multiplication (matrix multiply with [3,1,1; 1,3,1; 1,1,3])
            uint256 s0 = addmod(addmod(mulmod(3, state[0], P), state[1], P), state[2], P);
            uint256 s1 = addmod(addmod(state[0], mulmod(3, state[1], P), P), state[2], P);
            uint256 s2 = addmod(addmod(state[0], state[1], P), mulmod(3, state[2], P), P);
            state[0] = s0;
            state[1] = s1;
            state[2] = s2;

            // Add forward round constants
            state[0] = addmod(state[0], ROUND_CONSTANTS[r * 6], P);
            state[1] = addmod(state[1], ROUND_CONSTANTS[r * 6 + 1], P);
            state[2] = addmod(state[2], ROUND_CONSTANTS[r * 6 + 2], P);

            // Inverse S-box: x → x^(1/7) mod (p-1)
            // 7^{-1} mod (p-1) = 12507567355336728698426517568718442907741922514523448196398973820900461997495
            state[0] = powmod(state[0], 12507567355336728698426517568718442907741922514523448196398973820900461997495, P);
            state[1] = powmod(state[1], 12507567355336728698426517568718442907741922514523448196398973820900461997495, P);
            state[2] = powmod(state[2], 12507567355336728698426517568718442907741922514523448196398973820900461997495, P);

            // MDS multiplication
            s0 = addmod(addmod(mulmod(3, state[0], P), state[1], P), state[2], P);
            s1 = addmod(addmod(state[0], mulmod(3, state[1], P), P), state[2], P);
            s2 = addmod(addmod(state[0], state[1], P), mulmod(3, state[2], P), P);
            state[0] = s0;
            state[1] = s1;
            state[2] = s2;

            // Add inverse round constants
            state[0] = addmod(state[0], ROUND_CONSTANTS[r * 6 + 3], P);
            state[1] = addmod(state[1], ROUND_CONSTANTS[r * 6 + 4], P);
            state[2] = addmod(state[2], ROUND_CONSTANTS[r * 6 + 5], P);
        }

        // Output is the first state element (capacity element absorbs input)
        return state[0];
    }

    /// @dev Modular exponentiation using repeated squaring
    function powmod(uint256 base, uint256 exponent, uint256 modulus) internal pure returns (uint256) {
        if (modulus == 1) return 0;
        if (exponent == 0) return 1;
        if (base == 0) return 0;

        uint256 result = 1;
        base = base % modulus;

        while (exponent > 0) {
            if (exponent % 2 == 1) {
                result = mulmod(result, base, modulus);
            }
            exponent = exponent >> 1;
            base = mulmod(base, base, modulus);
        }

        return result;
    }
}
