import type { RequiredFix, Disposition } from "./release";

/**
 * Generate a markdown export of the IVE release report.
 *
 * This produces a self-contained markdown document capturing the disposition,
 * rationale, required fixes, and pipeline preservation state. Evaluators can
 * download this as an auditable record of the release decision.
 */
export function generateReleaseReportMarkdown(opts: {
  disposition: Disposition;
  rationale: string;
  fixes: RequiredFix[];
  runId: string;
  generatedAt: string;
}): string {
  const { disposition, rationale, fixes, runId, generatedAt } = opts;
  const blockers = fixes.filter((f) => f.blocksSubmission);
  const lines: string[] = [];

  lines.push("# IVE Release Readiness Report");
  lines.push("");
  lines.push(`**Generated:** ${generatedAt}`);
  lines.push(`**Run ID:** ${runId}`);
  lines.push(`**Platform:** VVU Integrated Verification Environment (IVE)`);
  lines.push(`**Demonstration Application:** HBK MK-II Hydro-Gateway`);
  lines.push("");

  lines.push("## Final Disposition");
  lines.push("");
  lines.push(`> **${disposition}**`);
  lines.push("");
  lines.push(rationale);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(`- Total required fixes: ${fixes.length}`);
  lines.push(`- Blocking submission: ${blockers.length}`);
  lines.push(`- Non-blocking: ${fixes.length - blockers.length}`);
  lines.push("");

  lines.push("## Required Fixes");
  lines.push("");
  lines.push("| ID | Severity | Affected File / Component | Blocks Submission | Minimum Action |");
  lines.push("|----|----------|---------------------------|-------------------|----------------|");
  for (const f of fixes) {
    const action = f.minimumAction.replace(/\|/g, "\\|").replace(/\n/g, " ");
    const file = f.affectedFile.replace(/\|/g, "\\|");
    lines.push(
      `| ${f.id} | ${f.severity} | ${file} | ${f.blocksSubmission ? "YES" : "NO"} | ${action} |`,
    );
  }
  lines.push("");

  lines.push("### Evidence Detail");
  lines.push("");
  for (const f of fixes) {
    lines.push(`#### ${f.id} — ${f.severity}`);
    lines.push("");
    lines.push(`**Affected:** ${f.affectedFile}`);
    lines.push("");
    lines.push(`**Evidence:** ${f.evidence}`);
    lines.push("");
    lines.push(`**Minimum corrective action:** ${f.minimumAction}`);
    lines.push("");
    lines.push(`**Blocks submission:** ${f.blocksSubmission ? "YES" : "NO"}`);
    lines.push("");
  }

  lines.push("## Pipeline Execution Preservation");
  lines.push("");
  lines.push("- The existing pipeline execution is retained and not rejected.");
  lines.push("- Historical run artifacts remain byte-for-byte unchanged.");
  lines.push("- Rerun is not required unless no existing execution satisfies the frozen release requirements.");
  lines.push("- An incomplete IVE adapter or dashboard is not justification for repeating the pipeline execution.");
  lines.push("");

  lines.push("## Engineering Position");
  lines.push("");
  lines.push("IVE does not claim physical certification, engineering approval, code compliance, or deployment authorization.");
  lines.push("It demonstrates bounded formal proof, deterministic execution, reproducible evidence, and cryptographic provenance.");
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("*This report was generated by the VVU IVE workspace. Every claim is traceable to repository evidence.*");

  return lines.join("\n");
}

/** Trigger a browser download of a text file with the given content. */
export function downloadTextFile(filename: string, content: string, mimeType = "text/markdown") {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke the URL after a short delay to ensure the download starts.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/** Copy text to the clipboard, returning true on success. */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof window === "undefined" || !navigator.clipboard) return false;
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
