/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VvuWarRoomPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var WAR_ROOM_VIEW_TYPE = "vvu-war-room-view";
var WarRoomView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return WAR_ROOM_VIEW_TYPE;
  }
  getDisplayText() {
    return "VVU War Room";
  }
  getIcon() {
    return "shield";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.createEl("h2", { text: "VVU War Room" });
    container.createEl("p", { text: "Operational dashboard placeholder. Wire real telemetry here." });
  }
};
var DEFAULT_SETTINGS = {
  dailyNoteFolder: "daily",
  complianceFolder: "compliance",
  gatewayUrl: "http://127.0.0.1:18789",
  gatewayToken: "",
  openclawEnabled: false
};
var VvuWarRoomPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(
      WAR_ROOM_VIEW_TYPE,
      (leaf) => new WarRoomView(leaf, this)
    );
    this.addRibbonIcon("shield", "Open VVU War Room", () => {
      this.activateView();
    });
    this.addRibbonIcon("calendar", "New VVU Daily Note", () => {
      this.createDailyNote();
    });
    this.addCommand({
      id: "open-war-room",
      name: "Open VVU War Room",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "new-daily-note",
      name: "Create VVU daily note",
      callback: () => this.createDailyNote()
    });
    this.addCommand({
      id: "insert-compliance-link",
      name: "Insert compliance document link",
      editorCallback: (editor) => this.insertComplianceLink(editor)
    });
    this.addCommand({
      id: "search-compliance",
      name: "Search vault for compliance items",
      callback: () => this.searchCompliance()
    });
    this.addCommand({
      id: "trigger-gateway-event",
      name: "Send test event to OpenClaw gateway",
      callback: () => this.sendGatewayEvent()
    });
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar();
    this.addSettingTab(new VvuWarRoomSettingTab(this.app, this));
  }
  onunload() {
  }
  // ─── Views ────────────────────────────────────────────────────────────────
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(WAR_ROOM_VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await (leaf == null ? void 0 : leaf.setViewState({ type: WAR_ROOM_VIEW_TYPE, active: true }));
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  // ─── Daily Notes ───────────────────────────────────────────────────────────
  async createDailyNote() {
    const now = /* @__PURE__ */ new Date();
    const dateStr = now.toISOString().slice(0, 10);
    const folder = this.settings.dailyNoteFolder.replace(/\/+$/, "");
    const fileName = `${folder}/${dateStr}.md`;
    let file = this.app.vault.getAbstractFileByPath(fileName);
    if (!file) {
      await this.ensureFolder(folder);
      await this.app.vault.create(fileName, this.dailyNoteTemplate(dateStr));
      file = this.app.vault.getAbstractFileByPath(fileName);
      new import_obsidian.Notice(`Created daily note: ${fileName}`);
    } else {
      new import_obsidian.Notice(`Daily note already exists: ${fileName}`);
    }
    await this.app.workspace.openLinkText(fileName, "");
  }
  dailyNoteTemplate(date) {
    return `# VVU War Room \u2014 ${date}

## Daily Standup
- [ ] Item 1
- [ ] Item 2
- [ ] Item 3

## OpenClaw Status
<!-- Gateway connectivity check: ${this.settings.gatewayUrl} -->

## Compliance Pulse
- FSCA filings:
- POPIA incidents:
- SAR/STR register updates:

## Incident Log
| Time | Severity | Description | Status |
|------|----------|-------------|--------|
|      |          |             |        |

## Action Items
- [ ] 

## Notes
`;
  }
  // ─── Compliance Quick-Links ────────────────────────────────────────────────
  async insertComplianceLink(editor) {
    const files = this.app.vault.getMarkdownFiles();
    const complianceFiles = files.filter(
      (f) => f.path.startsWith(this.settings.complianceFolder)
    );
    if (complianceFiles.length === 0) {
      new import_obsidian.Notice("No compliance documents found in " + this.settings.complianceFolder);
      return;
    }
    const chosen = complianceFiles[0];
    const link = `[[${chosen.path.replace(/\.md$/, "")}]]`;
    editor.replaceRange(link, editor.getCursor());
    new import_obsidian.Notice(`Inserted: ${chosen.name}`);
  }
  async searchCompliance() {
    const query = "compliance";
    const files = this.app.vault.getMarkdownFiles();
    const results = files.filter(
      (f) => f.path.toLowerCase().includes(query.toLowerCase())
    );
    if (results.length === 0) {
      new import_obsidian.Notice("No compliance files found");
      return;
    }
    const list = results.map((f) => `- [[${f.path.replace(/\.md$/, "")}]]`).join("\n");
    await this.app.workspace.openLinkText("", "");
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (activeView == null ? void 0 : activeView.editor) {
      activeView.editor.replaceRange("\n## Compliance Search Results\n\n" + list + "\n", activeView.editor.getCursor());
    }
    new import_obsidian.Notice(`Found ${results.length} compliance files`);
  }
  // ─── OpenClaw Gateway Integration ──────────────────────────────────────────
  async sendGatewayEvent() {
    if (!this.settings.openclawEnabled) {
      new import_obsidian.Notice("OpenClaw integration disabled in settings");
      return;
    }
    const url = `${this.settings.gatewayUrl}/api/event`;
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...this.settings.gatewayToken ? { Authorization: `Bearer ${this.settings.gatewayToken}` } : {}
        },
        body: JSON.stringify({
          source: "vvu-war-room-plugin",
          type: "manual-test",
          timestamp: (/* @__PURE__ */ new Date()).toISOString()
        })
      });
      if (res.ok) {
        new import_obsidian.Notice("Gateway event sent successfully");
      } else {
        new import_obsidian.Notice(`Gateway responded ${res.status}`);
      }
    } catch (e) {
      new import_obsidian.Notice(`Gateway error: ${e.message}`);
    }
  }
  // ─── Helpers ───────────────────────────────────────────────────────────────
  async ensureFolder(path) {
    const folder = this.app.vault.getAbstractFileByPath(path);
    if (!folder) {
      await this.app.vault.createFolder(path);
    }
  }
  updateStatusBar() {
    this.statusBarItem.setText(
      `VVU | ${this.settings.openclawEnabled ? "OpenClaw: ON" : "OpenClaw: OFF"}`
    );
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.updateStatusBar();
  }
};
var VvuWarRoomSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "VVU War Room Settings" });
    new import_obsidian.Setting(containerEl).setName("Daily notes folder").setDesc("Folder where daily notes are created.").addText(
      (text) => text.setPlaceholder("daily").setValue(this.plugin.settings.dailyNoteFolder).onChange(async (value) => {
        this.plugin.settings.dailyNoteFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Compliance folder").setDesc("Root folder for compliance documents.").addText(
      (text) => text.setPlaceholder("compliance").setValue(this.plugin.settings.complianceFolder).onChange(async (value) => {
        this.plugin.settings.complianceFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("OpenClaw gateway URL").setDesc("Base URL of the running OpenClaw gateway.").addText(
      (text) => text.setPlaceholder("http://127.0.0.1:18789").setValue(this.plugin.settings.gatewayUrl).onChange(async (value) => {
        this.plugin.settings.gatewayUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Gateway token").setDesc("Optional bearer token for gateway auth.").addText(
      (text) => text.setPlaceholder("vvu-war-room-2026-local").setValue(this.plugin.settings.gatewayToken).onChange(async (value) => {
        this.plugin.settings.gatewayToken = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Enable OpenClaw integration").setDesc("Allow the plugin to send events to the gateway.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openclawEnabled).onChange(async (value) => {
        this.plugin.settings.openclawEnabled = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
