apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vvu-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: vvu
  source:
    repoURL: https://github.com/divhanimajokweni-ctrl/proofbridge-liner.git
    targetRevision: main
    path: deploy/argocd/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: vvu-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 10
